### ISSUE TITLE
Manage request permission name miss-match

### ISSUE THREAD

**Issue by shakyl333** [bvipul/generator#2]
![screenshot_gen1](https://user-images.githubusercontent.com/20857953/38736298-33694dee-3f49-11e8-9f3e-bd417e0b7b94.png)
I am getting different name of manage-request from database when I create a new module using generator. Please help me to resolve.

**Comment by bvipul** [comment]
@shakyl333 you can get the latest code by changing your composer.json and changing version number for this package to "dev-master" and composer update.
