### ISSUE TITLE
error in description 

### ISSUE THREAD

**Issue by pomazanbohdan** [bvipul/generator#3]
A Laravel **5.4** CRUD Generator Package for Laravel AdminPanel <https://github.com/viralsolani/laravel-adminpanel>

**Comment by bvipul** [comment]
Why 5.4?

**Comment by pomazanbohdan** [comment]
![image](https://user-images.githubusercontent.com/696713/42931840-6a8d0f08-8b49-11e8-908e-6c98ee08a41d.png)

**Comment by cygnet-bvipul** [comment]
right. Thanks. @Pomazan-Bogdan

**Comment by bvipul** [comment]
right. Thanks. @Pomazan-Bogdan
