### ISSUE TITLE
Module On and Off

### ISSUE THREAD

**Issue by stoneshaq** [bvipul/generator#4]
Is there a way to turn the modules on and from dashboard?

**Comment by bvipul** [comment]
Unfortunately, we don't have that option, do you have a suggestion on how we can do it? Although it is kept in require-dev so it won't bother you in production

**Comment by stoneshaq** [comment]
Can you please check this. https://github.com/nWidart/laravel-modules/blob/master/README.md

Might give an idea and thanks so much for all your time and effort to create this great boilerplate.

**Comment by bvipul** [comment]
@stoneshaq Thanks I will take a look
